In [1]:
import numpy as np

# 创建3x4的二维数组，元素为1到12
arr = np.arange(1, 13).reshape(3, 4)

# 1. 打印数组的形状、维度和数据类型
print("原始数组：")
print(arr)
print(f"形状：{arr.shape}")
print(f"维度：{arr.ndim}")
print(f"数据类型：{arr.dtype}")

# 2. 将数组元素乘以2
arr_x2 = arr * 2
print("\n乘以2后的数组：")
print(arr_x2)

# 3. 将数组重塑为4x3的形状
arr_reshaped = arr.reshape(4, 3)
print("\n重塑为4x3后的数组：")
print(arr_reshaped)

原始数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
形状：(3, 4)
维度：2
数据类型：int32

乘以2后的数组：
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

重塑为4x3后的数组：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
