In [1]:
import numpy as np

# 定义 4x4 数组
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# 1. 提取第 2 行所有元素（注意：索引从 0 开始）
row_2 = array[1, :]
print("第 2 行所有元素：", row_2)

# 2. 提取第 3 列所有元素（注意：索引从 0 开始）
col_3 = array[:, 2]
print("第 3 列所有元素：", col_3)

# 3. 提取子数组（包含第 1、2 行和第 2、3 列）
sub_array = array[0:2, 1:3]
print("子数组（第 1、2 行和第 2、3 列）：")
print(sub_array)

# 4. 将大于 10 的元素替换为 0，打印修改后的数组
modified_array = array.copy()
modified_array[modified_array > 10] = 0
print("修改后（大于 10 的元素替换为 0）的数组：")
print(modified_array)

第 2 行所有元素： [5 6 7 8]
第 3 列所有元素： [ 3  7 11 15]
子数组（第 1、2 行和第 2、3 列）：
[[2 3]
 [6 7]]
修改后（大于 10 的元素替换为 0）的数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]
