In [1]:
import numpy as np

# 创建数组A：3x2的二维数组，元素为1到6
array_a = np.arange(1, 7).reshape(3, 2)
# 创建数组B：一维数组，元素为[10, 20]
array_b = np.array([10, 20])

print("数组A：")
print(array_a)
print("数组B：")
print(array_b)

# 1. 计算A和B的逐元素相加（利用广播）
add_result = array_a + array_b
print("\n任务1：A和B逐元素相加结果：")
print(add_result)

# 2. 计算A和B的逐元素相乘（利用广播）
multiply_result = array_a * array_b
print("\n任务2：A和B逐元素相乘结果：")
print(multiply_result)

# 3. 计算A的每一行与B的点积
dot_result = np.dot(array_a, array_b)
print("\n任务3：A的每一行与B的点积结果：")
print(dot_result)

数组A：
[[1 2]
 [3 4]
 [5 6]]
数组B：
[10 20]

任务1：A和B逐元素相加结果：
[[11 22]
 [13 24]
 [15 26]]

任务2：A和B逐元素相乘结果：
[[ 10  40]
 [ 30  80]
 [ 50 120]]

任务3：A的每一行与B的点积结果：
[ 50 110 170]
