In [1]:
import numpy as np

# 创建3x4的二维数组，元素为1到12
arr = np.arange(1, 13).reshape(3, 4)

# 1. 打印数组的形状、维度和数据类型
print("原始数组：")
print(arr)
print(f"形状：{arr.shape}")
print(f"维度：{arr.ndim}")
print(f"数据类型：{arr.dtype}")

# 2. 将数组元素乘以2
arr_x2 = arr * 2
print("\n乘以2后的数组：")
print(arr_x2)

# 3. 将数组重塑为4x3的形状
arr_reshaped = arr.reshape(4, 3)
print("\n重塑为4x3后的数组：")
print(arr_reshaped)

原始数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
形状：(3, 4)
维度：2
数据类型：int32

乘以2后的数组：
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

重塑为4x3后的数组：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

# 定义 4x4 数组
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# 1. 提取第 2 行所有元素（注意：索引从 0 开始）
row_2 = array[1, :]
print("第 2 行所有元素：", row_2)

# 2. 提取第 3 列所有元素（注意：索引从 0 开始）
col_3 = array[:, 2]
print("第 3 列所有元素：", col_3)

# 3. 提取子数组（包含第 1、2 行和第 2、3 列）
sub_array = array[0:2, 1:3]
print("子数组（第 1、2 行和第 2、3 列）：")
print(sub_array)

# 4. 将大于 10 的元素替换为 0，打印修改后的数组
modified_array = array.copy()
modified_array[modified_array > 10] = 0
print("修改后（大于 10 的元素替换为 0）的数组：")
print(modified_array)

In [ ]:
import numpy as np

# 创建数组A：3x2的二维数组，元素为1到6
array_a = np.arange(1, 7).reshape(3, 2)
# 创建数组B：一维数组，元素为[10, 20]
array_b = np.array([10, 20])

print("数组A：")
print(array_a)
print("数组B：")
print(array_b)

# 1. 计算A和B的逐元素相加（利用广播）
add_result = array_a + array_b
print("\n任务1：A和B逐元素相加结果：")
print(add_result)

# 2. 计算A和B的逐元素相乘（利用广播）
multiply_result = array_a * array_b
print("\n任务2：A和B逐元素相乘结果：")
print(multiply_result)

# 3. 计算A的每一行与B的点积
dot_result = np.dot(array_a, array_b)
print("\n任务3：A的每一行与B的点积结果：")
print(dot_result)